config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :bookings
    resources :conversations
    resources :dogs
    resources :messages
    resources :stripe_customers

    root to: "users#index"
  end

  root to: 'home#index'

  get 'home/index'
  get 'home/sitter'
  post '/api/search' => 'home#search_api'

  resources :conversations do
    resources :messages
  end

  # Profile
  get '/profile' => 'profile#profile'
  post 'profile/update_profile'
  get '/user/:username' => 'profile#public_profile', :constraints => { :username => /[^\/]+/ }

  post '/search' => 'home#search'

  # Booking
  get 'booking/index'
  post '/book' => 'booking#new'
  post 'booking/create'
  post 'booking/accept'
  get 'booking/sitter'
  get '/booking/:booking_id' => 'booking#show'
  get '/complete/:booking_id' => 'booking#complete'

  # Pets
  get 'pets/sample'
  get 'pets/index'
  post 'pets/add'
  post 'pets/remove'
  post 'pets/api'

  post 'api/favourite'

  get '/favourites' => 'api#all'

  post 'rating/sitter'

  devise_for :users
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  # belongs_to :user, foreign_key: :cust_id
  belongs_to :customer, class_name: 'User', foreign_key: 'cust_id'
  belongs_to :provider, class_name: 'User', foreign_key: 'provider_id'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where('(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)', sender_id,recipient_id, recipient_id, sender_id)
    end
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime('%m/%d/%y at %l:%M %p')
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
end

app/models/rating_sitter.rb
class RatingSitter < ActiveRecord::Base
  validates_uniqueness_of :booking_id
end

app/models/stripe_customer.rb
class StripeCustomer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs
  has_many :pets
  has_many :messages
  # has_many :bookings, foreign_key: 'cust_id'
  has_many :my_bookings,        class_name: 'Booking', foreign_key: 'cust_id'
  has_many :requested_bookings, class_name: 'Booking', foreign_key: 'provider_id'

  enum role: [:sitter, :customer]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :customer
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  validates_presence_of :username
  validates_uniqueness_of :username

  # This could replace has_many :bookings
  # def bookings
  #  Booking.where("cust_id = ? OR provider_id = ?", self.id, self.id)
  # end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def favourite
    f = Favourite.find_by(cust_id: current_user.id, provider_id: params[:userID])
    if f
      Favourite.find_by(cust_id: current_user.id, provider_id: params[:userID]).delete
      render json: {
        response: 'unfavourite'
      }
    else
      Favourite.create(
        cust_id: current_user.id,
        provider_id: params[:userID]
      )
      render json: {
        response: 'favourite'
      }
    end
  end

  def all
    @favourites = Favourite.where(cust_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:sitter]

  require 'haversine'

  def index
  end

  def sitter
    @users = User.where(role: 0).limit(10)
  end

  def search
    @lng = params[:lng].to_f
    @lat = params[:lat].to_f
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @location_query = params[:autocomplete]

    query = [@lat, @lng]

    @users = Array.new
    # @users = User.all

    User.where(role: 0).each do |user|

      if user_signed_in?
        if user == current_user
          next
        end
      end

      boolBook = true

      unless @start_date.empty? && @end_date.empty?
        Booking.where(provider_id: user.id).each do |booking|
          if @start_date.to_date <= booking.end_date && @end_date.to_date >= booking.start_date
            boolBook = false
          end
          break if boolBook == false
        end
      end

      if boolBook == true
        unless user.lat.nil? && user.lng.nil?
          user_coor = [user.lat, user.lng]

          if Haversine.distance(query, user_coor).to_km < 20
            @users << user
          end
        end
      end
    end

    @users = @users[0..20]
  end

  def search_api
    lng = params[:lng].to_f
    lat = params[:lat].to_f
    start_date = params[:start_date]
    end_date = params[:end_date]
    location_query = params[:autocomplete]

    query = [lat, lng]

    users = Array.new
    # @users = User.all

    User.where(role: 0).each do |user|

      if user_signed_in?
        if user == current_user
          next
        end
      end

      boolBook = true

      unless start_date.empty? && end_date.empty?
        Booking.where(provider_id: user.id).each do |booking|
          if start_date.to_date <= booking.end_date && end_date.to_date >= booking.start_date
            boolBook = false
          end
          break if boolBook == false
        end
      end

      if boolBook == true
        unless user.lat.nil? && user.lng.nil?
          user_coor = [user.lat, user.lng]

          if Haversine.distance(query, user_coor).to_km < 20
            users << user
          end
        end
      end
    end

    userArray = Array.new

    users[0..20].each do |user|
      fav = false
      if user_signed_in?
        if Favourite.find_by(cust_id: current_user.id, provider_id: user.id)
          fav = true
        end
      end
      userArray << {
        username: user.username,
        first_name: user.first_name,
        last_name: user.last_name,
        lat: user.lat,
        lng: user.lng
      }
    end

    render json: {
      users: userArray
    }
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def us_states
    [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
  end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/views/layouts/_messages.html.erb
<script type="text/javascript">
  setTimeout(function() {
    $('.alert-danger').fadeOut('slow');
  }, 4000);
  setTimeout(function() {
    $('.alert-success').fadeOut('slow');
  }, 4000);
  setTimeout(function() {
    $('.alert-notice').fadeOut('slow');
  }, 4000);
</script>

<% flash.each do |name, msg| %>
    <div class="alert alert-dismissable alert-<%= name %>" role="alert">
      <%= content_tag :div, msg, class: name %>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "PetsHosts", root_url, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>

        <li><%= link_to "Find a Sitter", home_sitter_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "Your Pets", pets_index_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Account", edit_user_registration_path %></li>
                <li><%= link_to "My Profile", profile_path %></li>
                <li><%= link_to "My Messages", conversations_path %></li>
                <li><%= link_to 'Favorite Sitters', favourites_path %></li>
                <% if current_user.sitter? %>
                    <li><%= link_to 'Booking Requests', booking_sitter_url %></li>
                <% end %>
                <li><%= link_to "My Bookings", booking_index_url %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Signup", new_user_registration_url %></li>
            <li><%= link_to "Login", new_user_session_url %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetsHosts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//maps.googleapis.com/maps/api/js?key=AIzaSyBBYiiD8XSVnbCc96hv5GTLhM-8VHuQgbc&v=3.exp&libraries=visualization,places' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
</html>